### ISSUE TITLE
Abstract classes vs. Interfaces and Chain of Responsibility

### ISSUE THREAD

**Issue by TheWinrarz** [ValorCat/Teem-Too#5]
We should discuss using abstract class vs interfaces for the Trackers

Doesn't matter which, but we should meet up to weigh the pros and cons of each so we can make a decision.

**Comment by ValorCat** [comment]
I was actually thinking about that this morning. An abstract class is objectively more powerful, particularly since l don't think we should use many default methods. I'd be okay with changing it to an abstract class, though I'm AFK right now so I can't easily look over everything myself.

**Comment by ValorCat** [comment]
I was working on the trackers and reached a point where it became obvious that an abstract class was necessary (it needed persistant state), so I implemented it that way. We can fairly easily change it back later if necessary.
